"""Host-resolution decision reason-code constants."""

from __future__ import annotations

DECISION_REASON_CODE_HOST_RESOLUTION_SKIPPED = "host_resolution_skipped"
DECISION_REASON_CODE_HOST_RESOLUTION_RESOLVES = "host_resolution_resolves"
DECISION_REASON_CODE_HOST_RESOLUTION_RESOLVED_WITHOUT_IP_ADDRESSES = (
    "host_resolution_resolved_without_ip_addresses"
)
DECISION_REASON_CODE_HOST_RESOLUTION_TIMEOUT = "host_resolution_timeout"
DECISION_REASON_CODE_HOST_RESOLUTION_SERVFAIL = "host_resolution_servfail"
DECISION_REASON_CODE_HOST_RESOLUTION_NXDOMAIN = "host_resolution_nxdomain"
DECISION_REASON_CODE_HOST_RESOLUTION_NODATA = "host_resolution_nodata"

HOST_RESOLUTION_REVIEW_DECISION_REASON_CODES = frozenset(
    {
        DECISION_REASON_CODE_HOST_RESOLUTION_TIMEOUT,
        DECISION_REASON_CODE_HOST_RESOLUTION_SERVFAIL,
        DECISION_REASON_CODE_HOST_RESOLUTION_NXDOMAIN,
        DECISION_REASON_CODE_HOST_RESOLUTION_NODATA,
        DECISION_REASON_CODE_HOST_RESOLUTION_RESOLVED_WITHOUT_IP_ADDRESSES,
    }
)
