"""Explicit classification constants shared across the DNS actionability pipeline."""

from __future__ import annotations

CLASSIFICATION_INPUT_PUBLIC_SUFFIX = "input_public_suffix"
CLASSIFICATION_MANUAL_FILTER_PASSED = "manual_filter_passed"
CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES = "manual_filter_pass_not_in_sources"
CLASSIFICATION_MANUAL_FILTER_OUT = "manual_filter_out"
CLASSIFICATION_MANUAL_FILTER_OUT_NOT_IN_SOURCES = "manual_filter_out_not_in_sources"
CLASSIFICATION_MANUAL_ADD_ACTIONABLE = "manual_add_actionable"

CLASSIFICATION_DNS_DELEGATION_EXISTS = "dns_delegation_exists"
CLASSIFICATION_DNS_DELEGATION_NXDOMAIN = "dns_delegation_nxdomain"
CLASSIFICATION_DNS_DELEGATION_NODATA = "dns_delegation_nodata"
CLASSIFICATION_DNS_DELEGATION_NO_NAMESERVERS = "dns_delegation_no_nameservers"
CLASSIFICATION_DNS_DELEGATION_TIMEOUT = "dns_delegation_timeout"
CLASSIFICATION_DNS_DELEGATION_SERVFAIL = "dns_delegation_servfail"

# Host-resolution classifications keep their existing string values for output
# compatibility. They describe only the optional A/AAAA/CNAME stage, never the
# mandatory NS delegation stage above.
CLASSIFICATION_HOST_RESOLUTION_SKIPPED = "dns_host_resolution_skipped"
CLASSIFICATION_DNS_RESOLVES = "dns_resolves"
CLASSIFICATION_DNS_RESOLVED_WITHOUT_IP_ADDRESSES = "dns_resolved_without_ip_addresses"
CLASSIFICATION_DNS_LOOKUP_TIMEOUT = "dns_lookup_timeout"
CLASSIFICATION_DNS_LOOKUP_SERVFAIL = "dns_lookup_servfail"
CLASSIFICATION_DNS_HOST_NXDOMAIN = "dns_host_nxdomain"
CLASSIFICATION_DNS_HOST_NODATA = "dns_host_nodata"

CLASSIFICATION_GEO_LOOKUP_FAILED = "geo_lookup_failed"
CLASSIFICATION_GEO_POLICY_ACCEPTED = "geo_policy_accepted"
CLASSIFICATION_GEO_POLICY_REJECTED = "geo_policy_rejected"
CLASSIFICATION_GEO_REGION_NAME_UNAVAILABLE = "geo_region_name_unavailable"

# Legacy public review label retained for compatibility; new delegation
# timeout/SERVFAIL rows emit their stage-specific classifications below.
REVIEW_CLASSIFICATION_DNS_DELEGATION_FILTERED_OUT = "dns_delegation_filtered_out"
REVIEW_CLASSIFICATION_DNS_DELEGATION_TIMEOUT = CLASSIFICATION_DNS_DELEGATION_TIMEOUT
REVIEW_CLASSIFICATION_DNS_DELEGATION_SERVFAIL = CLASSIFICATION_DNS_DELEGATION_SERVFAIL
REVIEW_CLASSIFICATION_DNS_HOST_RESOLUTION_FILTERED_OUT = (
    "dns_host_resolution_filtered_out"
)
REVIEW_CLASSIFICATION_GEO_FILTERED_OUT = "geo_filtered_out"
REVIEW_CLASSIFICATION_INPUT_PUBLIC_SUFFIX = "input_public_suffix"
REVIEW_CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES = (
    "manual_filter_pass_not_in_sources"
)
REVIEW_CLASSIFICATION_MANUAL_FILTERED_OUT = "manual_filtered_out"

DELEGATION_UNACTIONABLE_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_DNS_DELEGATION_NXDOMAIN,
        CLASSIFICATION_DNS_DELEGATION_NODATA,
        CLASSIFICATION_DNS_DELEGATION_NO_NAMESERVERS,
    }
)

DELEGATION_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_DNS_DELEGATION_TIMEOUT,
        CLASSIFICATION_DNS_DELEGATION_SERVFAIL,
    }
)

HOST_RESOLUTION_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_DNS_LOOKUP_TIMEOUT,
        CLASSIFICATION_DNS_LOOKUP_SERVFAIL,
        CLASSIFICATION_DNS_HOST_NXDOMAIN,
        CLASSIFICATION_DNS_HOST_NODATA,
        CLASSIFICATION_DNS_RESOLVED_WITHOUT_IP_ADDRESSES,
    }
)

DNS_REVIEW_CLASSIFICATIONS = frozenset(
    {
        *DELEGATION_REVIEW_CLASSIFICATIONS,
        *HOST_RESOLUTION_REVIEW_CLASSIFICATIONS,
    }
)

GEO_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_GEO_LOOKUP_FAILED,
        CLASSIFICATION_GEO_POLICY_REJECTED,
        CLASSIFICATION_GEO_REGION_NAME_UNAVAILABLE,
    }
)

ROUTE_FILTERED_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_DNS_DELEGATION_EXISTS,
        CLASSIFICATION_HOST_RESOLUTION_SKIPPED,
        CLASSIFICATION_DNS_RESOLVES,
        CLASSIFICATION_GEO_POLICY_ACCEPTED,
        CLASSIFICATION_MANUAL_FILTER_PASSED,
        CLASSIFICATION_MANUAL_ADD_ACTIONABLE,
    }
)
ROUTE_UNACTIONABLE_CLASSIFICATIONS = DELEGATION_UNACTIONABLE_CLASSIFICATIONS
ROUTE_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_INPUT_PUBLIC_SUFFIX,
        CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES,
        CLASSIFICATION_MANUAL_FILTER_OUT,
        CLASSIFICATION_MANUAL_FILTER_OUT_NOT_IN_SOURCES,
        *DNS_REVIEW_CLASSIFICATIONS,
        *GEO_REVIEW_CLASSIFICATIONS,
    }
)

PUBLIC_REVIEW_CLASSIFICATIONS = frozenset(
    {
        REVIEW_CLASSIFICATION_DNS_DELEGATION_FILTERED_OUT,
        REVIEW_CLASSIFICATION_DNS_DELEGATION_TIMEOUT,
        REVIEW_CLASSIFICATION_DNS_DELEGATION_SERVFAIL,
        REVIEW_CLASSIFICATION_DNS_HOST_RESOLUTION_FILTERED_OUT,
        REVIEW_CLASSIFICATION_GEO_FILTERED_OUT,
        REVIEW_CLASSIFICATION_INPUT_PUBLIC_SUFFIX,
        REVIEW_CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES,
        REVIEW_CLASSIFICATION_MANUAL_FILTERED_OUT,
    }
)
