"""Explicit classification constants shared across the pipeline."""

from __future__ import annotations

ROOT_CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_REGISTERED = (
    "rdap_registrable_domain_registered"
)
ROOT_CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_UNREGISTERED = (
    "rdap_registrable_domain_unregistered"
)
ROOT_CLASSIFICATION_RDAP_LOOKUP_UNAVAILABLE = "rdap_lookup_unavailable"
ROOT_CACHE_CLASSIFICATIONS = frozenset(
    {
        ROOT_CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_REGISTERED,
        ROOT_CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_UNREGISTERED,
        ROOT_CLASSIFICATION_RDAP_LOOKUP_UNAVAILABLE,
    }
)

CLASSIFICATION_INPUT_PUBLIC_SUFFIX = "input_public_suffix"
CLASSIFICATION_MANUAL_FILTER_PASSED = "manual_filter_passed"
CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES = "manual_filter_pass_not_in_sources"
CLASSIFICATION_MANUAL_FILTER_OUT = "manual_filter_out"
CLASSIFICATION_MANUAL_FILTER_OUT_NOT_IN_SOURCES = "manual_filter_out_not_in_sources"
CLASSIFICATION_MANUAL_ADD_REGISTERED = "manual_add_registered"
CLASSIFICATION_MANUAL_ADD_UNREGISTERED = "manual_add_unregistered"
CLASSIFICATION_MANUAL_ADD_UNAVAILABLE = "manual_add_unavailable"
CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_UNREGISTERED = (
    ROOT_CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_UNREGISTERED
)
CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_REGISTERED_DNS_DISABLED = (
    "rdap_registrable_domain_registered_dns_disabled"
)
CLASSIFICATION_RDAP_LOOKUP_UNAVAILABLE_DNS_DISABLED = (
    "rdap_lookup_unavailable_dns_disabled"
)
CLASSIFICATION_DNS_LOOKUP_TIMEOUT = "dns_lookup_timeout"
CLASSIFICATION_DNS_LOOKUP_SERVFAIL = "dns_lookup_servfail"
CLASSIFICATION_DNS_REGISTERED_APEX_NXDOMAIN = "dns_registered_apex_nxdomain"
CLASSIFICATION_DNS_REGISTERED_APEX_NODATA = "dns_registered_apex_nodata"
CLASSIFICATION_DNS_REGISTERED_SUBDOMAIN_NXDOMAIN = "dns_registered_subdomain_nxdomain"
CLASSIFICATION_DNS_REGISTERED_SUBDOMAIN_NODATA = "dns_registered_subdomain_nodata"
CLASSIFICATION_RDAP_STATUS_INACTIVE = "rdap_registered_domain_status_inactive"
CLASSIFICATION_RDAP_STATUS_CLIENT_HOLD = "rdap_registered_domain_status_client_hold"
CLASSIFICATION_RDAP_STATUS_SERVER_HOLD = "rdap_registered_domain_status_server_hold"
CLASSIFICATION_RDAP_STATUS_HOLD_OTHER = "rdap_registered_domain_status_hold_other"
CLASSIFICATION_RDAP_STATUS_REDEMPTION_PERIOD = (
    "rdap_registered_domain_status_redemption_period"
)
CLASSIFICATION_RDAP_STATUS_PENDING_DELETE = (
    "rdap_registered_domain_status_pending_delete"
)
CLASSIFICATION_RDAP_STATUS_PENDING_RESTORE = (
    "rdap_registered_domain_status_pending_restore"
)
CLASSIFICATION_RDAP_STATUS_PENDING_RENEW = "rdap_registered_domain_status_pending_renew"
CLASSIFICATION_RDAP_STATUS_DELETION_OTHER = (
    "rdap_registered_domain_status_deletion_other"
)
CLASSIFICATION_DNS_RESOLVES = "dns_resolves"
CLASSIFICATION_DNS_RESOLVED_WITHOUT_IP_ADDRESSES = "dns_resolved_without_ip_addresses"
CLASSIFICATION_GEO_LOOKUP_FAILED = "geo_lookup_failed"
CLASSIFICATION_GEO_REGION_NAME_UNAVAILABLE = "geo_region_name_unavailable"
CLASSIFICATION_GEO_POLICY_REJECTED = "geo_policy_rejected"

REVIEW_CLASSIFICATION_DNS_FILTERED_OUT = "dns_filtered_out"
REVIEW_CLASSIFICATION_GEO_FILTERED_OUT = "geo_filtered_out"
REVIEW_CLASSIFICATION_INPUT_PUBLIC_SUFFIX = "input_public_suffix"
REVIEW_CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES = (
    CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES
)
REVIEW_CLASSIFICATION_MANUAL_FILTERED_OUT = "manual_filtered_out"
REVIEW_CLASSIFICATION_RDAP_FILTERED_OUT = "rdap_filtered_out"
PUBLIC_REVIEW_CLASSIFICATIONS = frozenset(
    {
        REVIEW_CLASSIFICATION_DNS_FILTERED_OUT,
        REVIEW_CLASSIFICATION_GEO_FILTERED_OUT,
        REVIEW_CLASSIFICATION_INPUT_PUBLIC_SUFFIX,
        REVIEW_CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES,
        REVIEW_CLASSIFICATION_MANUAL_FILTERED_OUT,
        REVIEW_CLASSIFICATION_RDAP_FILTERED_OUT,
    }
)

RDAP_STATUS_CLASSIFICATIONS = {
    "inactive": CLASSIFICATION_RDAP_STATUS_INACTIVE,
    "clienthold": CLASSIFICATION_RDAP_STATUS_CLIENT_HOLD,
    "serverhold": CLASSIFICATION_RDAP_STATUS_SERVER_HOLD,
    "redemptionperiod": CLASSIFICATION_RDAP_STATUS_REDEMPTION_PERIOD,
    "pendingdelete": CLASSIFICATION_RDAP_STATUS_PENDING_DELETE,
    "pendingrestore": CLASSIFICATION_RDAP_STATUS_PENDING_RESTORE,
    "pendingrenew": CLASSIFICATION_RDAP_STATUS_PENDING_RENEW,
}
RDAP_STATUS_CLASSIFICATION_ORDER = (
    "inactive",
    "clienthold",
    "serverhold",
    "redemptionperiod",
    "pendingdelete",
    "pendingrestore",
    "pendingrenew",
)
RDAP_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_RDAP_STATUS_INACTIVE,
        CLASSIFICATION_RDAP_STATUS_CLIENT_HOLD,
        CLASSIFICATION_RDAP_STATUS_SERVER_HOLD,
        CLASSIFICATION_RDAP_STATUS_HOLD_OTHER,
        CLASSIFICATION_RDAP_STATUS_REDEMPTION_PERIOD,
        CLASSIFICATION_RDAP_STATUS_PENDING_DELETE,
        CLASSIFICATION_RDAP_STATUS_PENDING_RESTORE,
        CLASSIFICATION_RDAP_STATUS_PENDING_RENEW,
        CLASSIFICATION_RDAP_STATUS_DELETION_OTHER,
    }
)
PRE_GEO_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_DNS_LOOKUP_TIMEOUT,
        CLASSIFICATION_DNS_LOOKUP_SERVFAIL,
        CLASSIFICATION_MANUAL_FILTER_PASS_NOT_IN_SOURCES,
        CLASSIFICATION_MANUAL_FILTER_OUT,
        CLASSIFICATION_MANUAL_FILTER_OUT_NOT_IN_SOURCES,
        CLASSIFICATION_DNS_REGISTERED_APEX_NXDOMAIN,
        CLASSIFICATION_DNS_REGISTERED_APEX_NODATA,
        CLASSIFICATION_DNS_RESOLVED_WITHOUT_IP_ADDRESSES,
        *RDAP_REVIEW_CLASSIFICATIONS,
    }
)
GEO_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_GEO_LOOKUP_FAILED,
        CLASSIFICATION_GEO_REGION_NAME_UNAVAILABLE,
        CLASSIFICATION_GEO_POLICY_REJECTED,
    }
)
ROUTE_DEAD_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_UNREGISTERED,
    }
)
ROUTE_REVIEW_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_INPUT_PUBLIC_SUFFIX,
        CLASSIFICATION_RDAP_LOOKUP_UNAVAILABLE_DNS_DISABLED,
        CLASSIFICATION_MANUAL_ADD_UNREGISTERED,
        CLASSIFICATION_MANUAL_ADD_UNAVAILABLE,
        CLASSIFICATION_DNS_REGISTERED_SUBDOMAIN_NXDOMAIN,
        CLASSIFICATION_DNS_REGISTERED_SUBDOMAIN_NODATA,
        *PRE_GEO_REVIEW_CLASSIFICATIONS,
        *GEO_REVIEW_CLASSIFICATIONS,
    }
)
ROUTE_FILTERED_CLASSIFICATIONS = frozenset(
    {
        CLASSIFICATION_MANUAL_FILTER_PASSED,
        CLASSIFICATION_MANUAL_ADD_REGISTERED,
        CLASSIFICATION_RDAP_REGISTRABLE_DOMAIN_REGISTERED_DNS_DISABLED,
        CLASSIFICATION_DNS_RESOLVES,
    }
)
