"""Worker-local async runtime sizing constants."""

from __future__ import annotations

DELEGATION_STAGE_CONCURRENCY = 20
DNS_HOST_RESOLUTION_STAGE_CONCURRENCY = 20
IP_LOCATION_STAGE_CONCURRENCY = 8

DELEGATION_INPUT_QUEUE_SIZE = 512
DELEGATION_TO_HOST_RESOLUTION_QUEUE_SIZE = 512
HOST_RESOLUTION_TO_IP_LOCATION_QUEUE_SIZE = 512
RESULT_QUEUE_SIZE = 512
