"""Locked async runtime constants defined by the rewrite plan."""

from __future__ import annotations

from ..checking.domain_checker import DomainChecker

RDAP_RETRYABLE_HTTP_STATUSES = (408, 429, 502, 503, 504)
RDAP_MAX_ATTEMPTS = 4
RDAP_RETRY_AFTER_MIN_SECONDS = 1
RDAP_RETRY_AFTER_MAX_SECONDS = 30
RDAP_FALLBACK_BACKOFF_SECONDS = (1.0, 2.0, 4.0)
RDAP_FALLBACK_BACKOFF_MAX_SECONDS = 8.0

DNS_MAX_ATTEMPTS = DomainChecker.MAX_DNS_RETRY_ATTEMPTS
DNS_RETRY_BACKOFF_SECONDS = (0.1, 0.2, 0.4)

RDAP_STAGE_WORKERS = 8
DNS_STAGE_WORKERS = 8
GEO_STAGE_WORKERS = 8

PARSE_TO_RDAP_QUEUE_SIZE = 512
RDAP_TO_DNS_QUEUE_SIZE = 512
DNS_TO_GEO_QUEUE_SIZE = 512
RESULT_QUEUE_SIZE = 1024

ROOT_WRITER_QUEUE_SIZE = 512
DNS_WRITER_QUEUE_SIZE = 512
GEO_WRITER_QUEUE_SIZE = 512
