"""Async runtime sizing constants."""

from __future__ import annotations

DELEGATION_STAGE_WORKERS = 8
HOST_RESOLUTION_STAGE_WORKERS = 8
GEO_STAGE_WORKERS = 8

PARSE_TO_DELEGATION_QUEUE_SIZE = 512
DELEGATION_TO_HOST_RESOLUTION_QUEUE_SIZE = 512
HOST_RESOLUTION_TO_GEO_QUEUE_SIZE = 512
RESULT_QUEUE_SIZE = 512
DELEGATION_WRITER_QUEUE_SIZE = 512
HOST_RESOLUTION_WRITER_QUEUE_SIZE = 512
GEO_WRITER_QUEUE_SIZE = 512

DNS_STAGE_WORKERS = HOST_RESOLUTION_STAGE_WORKERS
DELEGATION_TO_DNS_QUEUE_SIZE = DELEGATION_TO_HOST_RESOLUTION_QUEUE_SIZE
DNS_TO_GEO_QUEUE_SIZE = HOST_RESOLUTION_TO_GEO_QUEUE_SIZE
DNS_WRITER_QUEUE_SIZE = HOST_RESOLUTION_WRITER_QUEUE_SIZE
