"""Domain checking and geo lookup components."""

from .domain_checker import (
    DNSResult,
    DEFAULT_ECS_FALLBACK_NAMESERVERS,
    DelegationResult,
    DomainChecker,
    HostResolutionResult,
    QUAD9_ECS_NAMESERVERS,
    RetryableDNSLookupError,
    classify,
    dns_resolver_key,
    effective_dns_nameservers,
)
from .ip_geo import (
    GEO_STATUS_CACHE_HIT,
    GEO_STATUS_INVALID_PAYLOAD,
    GEO_STATUS_OK,
    GEO_STATUS_PROVIDER_FAILURE,
    GEO_STATUS_RATE_LIMITED,
    GEO_STATUS_REQUEST_FAILED,
    GeoJSProvider,
    GeoPolicyDecision,
    IP2LocationIOProvider,
    IPGeoProvider,
    IPGeoResult,
    IPInfoLiteProvider,
    build_geo_provider,
    evaluate_geo_policy,
)

__all__ = [
    "DNSResult",
    "DEFAULT_ECS_FALLBACK_NAMESERVERS",
    "DelegationResult",
    "DomainChecker",
    "HostResolutionResult",
    "GEO_STATUS_CACHE_HIT",
    "GEO_STATUS_INVALID_PAYLOAD",
    "GEO_STATUS_OK",
    "GEO_STATUS_PROVIDER_FAILURE",
    "GEO_STATUS_RATE_LIMITED",
    "GEO_STATUS_REQUEST_FAILED",
    "GeoJSProvider",
    "GeoPolicyDecision",
    "IP2LocationIOProvider",
    "IPGeoProvider",
    "IPGeoResult",
    "IPInfoLiteProvider",
    "QUAD9_ECS_NAMESERVERS",
    "RetryableDNSLookupError",
    "build_geo_provider",
    "classify",
    "dns_resolver_key",
    "effective_dns_nameservers",
    "evaluate_geo_policy",
]
