"""Domain checking and geo lookup components."""

from .domain_checker import (
    CacheableRDAPUnavailableError,
    DNSResult,
    DomainChecker,
    MissingAuthoritativeBootstrapError,
    RDAPResult,
    RDAPUnavailableError,
    classify,
)
from .ip_geo import (
    GEO_STATUS_CACHE_HIT,
    GEO_STATUS_INVALID_PAYLOAD,
    GEO_STATUS_OK,
    GEO_STATUS_PROVIDER_FAILURE,
    GEO_STATUS_RATE_LIMITED,
    GEO_STATUS_REQUEST_FAILED,
    GeoJSProvider,
    GeoPolicyDecision,
    IP2LocationIOProvider,
    IPGeoProvider,
    IPGeoResult,
    IPInfoLiteProvider,
    build_geo_provider,
    evaluate_geo_policy,
)

__all__ = [
    "CacheableRDAPUnavailableError",
    "DNSResult",
    "DomainChecker",
    "GEO_STATUS_CACHE_HIT",
    "GEO_STATUS_INVALID_PAYLOAD",
    "GEO_STATUS_OK",
    "GEO_STATUS_PROVIDER_FAILURE",
    "GEO_STATUS_RATE_LIMITED",
    "GEO_STATUS_REQUEST_FAILED",
    "GeoJSProvider",
    "GeoPolicyDecision",
    "IP2LocationIOProvider",
    "IPGeoProvider",
    "IPGeoResult",
    "IPInfoLiteProvider",
    "MissingAuthoritativeBootstrapError",
    "RDAPResult",
    "RDAPUnavailableError",
    "build_geo_provider",
    "classify",
    "evaluate_geo_policy",
]
