"""Delegation decision reason-code constants."""

from __future__ import annotations

DECISION_REASON_CODE_DELEGATION_NS_RECORDS_EXIST = "delegation_ns_records_exist"
DECISION_REASON_CODE_DELEGATION_NS_NODATA = "delegation_ns_nodata"
DECISION_REASON_CODE_DELEGATION_NS_NXDOMAIN_SOA_EXISTS = (
    "delegation_ns_nxdomain_soa_exists"
)
DECISION_REASON_CODE_DELEGATION_NS_NXDOMAIN_SOA_ABSENT = (
    "delegation_ns_nxdomain_soa_absent"
)
DECISION_REASON_CODE_DELEGATION_NS_NXDOMAIN_SOA_RETRY_EXHAUSTED = (
    "delegation_ns_nxdomain_soa_retry_exhausted"
)
DECISION_REASON_CODE_DELEGATION_NS_RETRY_EXHAUSTED_SOA_EXISTS = (
    "delegation_ns_retry_exhausted_soa_exists"
)
DECISION_REASON_CODE_DELEGATION_NS_RETRY_EXHAUSTED_SOA_ABSENT = (
    "delegation_ns_retry_exhausted_soa_absent"
)
DECISION_REASON_CODE_DELEGATION_NS_RETRY_EXHAUSTED_SOA_RETRY_EXHAUSTED = (
    "delegation_ns_retry_exhausted_soa_retry_exhausted"
)
DECISION_REASON_CODE_DELEGATION_NS_EMPTY_ANSWER = "delegation_ns_empty_answer"
DECISION_REASON_CODE_DELEGATION_NS_LOOKUP_ERROR = "delegation_ns_lookup_error"

DELEGATION_UNACTIONABLE_DECISION_REASON_CODES = frozenset(
    {
        DECISION_REASON_CODE_DELEGATION_NS_NXDOMAIN_SOA_ABSENT,
        DECISION_REASON_CODE_DELEGATION_NS_EMPTY_ANSWER,
    }
)

DELEGATION_REVIEW_DECISION_REASON_CODES = frozenset(
    {
        DECISION_REASON_CODE_DELEGATION_NS_NXDOMAIN_SOA_RETRY_EXHAUSTED,
        DECISION_REASON_CODE_DELEGATION_NS_RETRY_EXHAUSTED_SOA_ABSENT,
        DECISION_REASON_CODE_DELEGATION_NS_RETRY_EXHAUSTED_SOA_RETRY_EXHAUSTED,
        DECISION_REASON_CODE_DELEGATION_NS_LOOKUP_ERROR,
    }
)
